name: checking k8s
on:
  push:
  workflow_dispatch:
jobs:
  dev-deploy:
    runs-on: [self-hosted, macOS, X64, dev]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.26.0'
      - uses: azure/k8s-set-context@v4
        with:
           method: kubeconfig
           kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: checking if k8s works
        run: |
          echo '-------------'
          kubectl get pods
          echo '-------------'
